### ISSUE TITLE
Bloodmagic 1.7.10 Переклад

### ISSUE THREAD

**Issue by ErikMensy** [SKZGx/UA-Translation#3]
[Ukr_UA.txt](https://github.com/SKZGx/UA-Translation/files/14624139/Ukr_UA.txt)
Потрібно замінити розширення файлу на .lang

**Comment by MEGATREX4** [comment]
надайте знову файл, будь ласка, або заповніть форму на вебсайті https://sumtranslate.netlify.app/addtranslation

**Comment by ErikMensy** [comment]
Заповнив форму
